version: '3.8'

services:
  laneful-csharp-examples:
    build:
      context: ..
      dockerfile: examples/Dockerfile
    environment:
      - LANEFUL_BASE_URL=${LANEFUL_BASE_URL}
      - LANEFUL_AUTH_TOKEN=${LANEFUL_AUTH_TOKEN}
      - LANEFUL_FROM_EMAIL=${LANEFUL_FROM_EMAIL}
      - LANEFUL_TO_EMAILS=${LANEFUL_TO_EMAILS}
      - LANEFUL_TEMPLATE_ID=${LANEFUL_TEMPLATE_ID}
      - LANEFUL_WEBHOOK_SECRET=${LANEFUL_WEBHOOK_SECRET}
      - LANEFUL_WEBHOOK_URL=${LANEFUL_WEBHOOK_URL}
    env_file:
      - .env
    command: ["all"]  # Run all examples by default
